float3 CameraPositionWS = LWCToFloat(ResolvedView.WorldCameraOrigin);
float3 CameraVectorWS = -Parameters.CameraVector;


Color = 0.0;
Dir = CameraVectorWS;

BlackHoleProperties BHP;
Mask = 1.0;

BHP.Mass = Mass;
BHP.EventHorizon = Mass*2.0;
BHP.DiskTexture = DiskTexture;
BHP.DiskTextureSampler = DiskTextureSampler;
BHP.DiskDensity = DiskDensity;
BHP.DiskDensityBias = DiskDensityBias;
BHP.DiskOuterRadius = DiskOuterRadius;
BHP.DiskInnerRadius = DiskInnerRadius;
BHP.FogDensity = FogDensity;
BHP.FogHeight = FogHeight;
BHP.FogExponent = FogExponent;
BHP.LightColor = LightColor;
BHP.LightIntensity = LightIntensity;
BHP.LightBias = LightBias;
BHP.ShadowColor = ShadowColor;
BHP.ShadowDensity = ShadowDensity;
BHP.ShadowStepSize = ShadowStepSize;

int3 randpos = int3(Parameters.SvPosition.xy, View.StateFrameIndexMod8);
float rand = float(Rand3DPCG16(randpos).x) / 0xffff;

float3 InitPos = CameraPositionWS;
float3 InitDir = CameraVectorWS;

Dir = CameraVectorWS;
InitPos += InitDir * rand * JitterAmount;

BlackHole(Color, Mask, Dir, InitPos, BHP);

return 1.0;