float3 CameraPositionWS = LWCToFloat(ResolvedView.WorldCameraOrigin);
float3 CameraVectorWS = -Parameters.CameraVector;


Color = 0.0;
Dir = CameraVectorWS;

BlackHoleProperties BHP;
Mask = 1.0;

BHP.Mass = Mass;
BHP.EventHorizon = Mass*2.0;
BHP.DiskTexture = DiskTexture;
BHP.DiskTextureSampler = DiskTextureSampler;
BHP.DiskDensity = DiskDensity;
BHP.DiskDensityBias = DiskDensityBias;
BHP.DiskOuterRadius = DiskOuterRadius;
BHP.DiskInnerRadius = DiskInnerRadius;
BHP.FogDensity = FogDensity;
BHP.FogHeight = FogHeight;
BHP.FogExponent = FogExponent;


BlackHole(Color, Mask, Dir, CameraPositionWS, BHP);

return 1.0;